parameters:
  configCustomerCanDeleteIsAccount: 0
  configCustomerExport: 0
  pathAdmin: "sylius_admin"
services:
# MISC
  eknow_gdpr_plugin.provider.logged_in_user:
    class: Eknow\GdprPlugin\Provider\LoggedInUserProvider
    arguments:
        - '@security.token_storage'

# CONTROLLER
  eknow_gdpr_plugin.controller.shop.account.delete:
    class: Eknow\GdprPlugin\Controller\Shop\Account\DeleteController
    arguments:
      - ["%configCustomerCanDeleteIsAccount%"]
      - "@eknow_gdpr_plugin.provider.logged_in_user"
      - "@sylius.repository.customer"
    tags:
        - { name: controller.service_arguments }
  eknow_gdpr_plugin.controller.shop.account.extract.personal:
    class: Eknow\GdprPlugin\Controller\Shop\Account\ExportPersonalDataController
    arguments:
      - "@eknow_gdpr_plugin.provider.logged_in_user"
      - "@sylius.repository.customer"
    tags:
        - { name: controller.service_arguments }
  eknow_gdpr_plugin.controller.shop.account.index:
    class: Eknow\GdprPlugin\Controller\Shop\Account\IndexController
    arguments:
      - ["%configCustomerCanDeleteIsAccount%"]
      - ["%configCustomerExport%"]
      - "@eknow_gdpr_plugin.provider.logged_in_user"
      - "@sylius.repository.customer"
    tags:
        - { name: controller.service_arguments }

# MENU
  eknow_gdpr_plugin.menu.menu_builder.main:
    class: Eknow\GdprPlugin\Menu\AdminMenuBuilder
    tags:
        - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }
  eknow_gdpr_plugin.menu.account_builder.main:
      class: Eknow\GdprPlugin\Menu\AccountMenuBuilder
      tags:
          - { name: kernel.event_listener, event: sylius.menu.shop.account, method: addAccountMenuItems }
